---
development:
  dialect: "sqlite3"
  database: /home/tgulacsi/src/github.com/UNO-SOFT/hotfix/hotfix_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/tgulacsi/src/github.com/UNO-SOFT/hotfix/hotfix_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/tgulacsi/src/github.com/UNO-SOFT/hotfix/hotfix_production.sqlite
